const routes = require('express').Router()

const cargo = require('./cargo')
const centroDeCusto = require('./centroDeCusto')
const contador = require('./contador')
const departamento = require('./departamento')
const sindicato = require('./sindicato')
const colaborador = require('./colaborador')
const periodoExperiencia = require('./periodoExperiencia')
const evento = require('./evento')
const lembrete = require('./lembrete')
const recado = require('./recado')
const endereco = require('./endereco')
const jornadaTrabalho = require('./jornadaTrabalho')
const vinculo = require('./vinculo')
const formaPagamento = require('./formaPagamento')
const contato = require('./contato')
const copiaDocumento = require('./copiaDocumento')
const checklist = require('./checkList')
const dependente = require('./dependente')
const banco = require('./banco')
const escolaridade = require('./escolaridade')
const beneficio = require('./beneficio')
const holerite = require('./holerite')
const fechamentoFolha = require('./fechamentoFolha')
const configuracao = require('./configuracao')
const feriado = require('./feriado')
const empresa = require('./empresa')
const cobranca = require('./cobranca')
const companhia = require('./companhia')
const usuario = require('./usuario')
const auth = require('./auth')

routes.get('/cargos/:id', auth.verifyToken, cargo.findById)
routes.get('/cargos', auth.verifyToken, cargo.list)
routes.post('/cargos', auth.verifyToken, cargo.save)
routes.put('/cargos', auth.verifyToken, cargo.update)
routes.delete('/cargos/:id', auth.verifyToken, cargo.delete)

routes.get('/departamentos/:id', auth.verifyToken, departamento.findById)
routes.get('/departamentos', auth.verifyToken, departamento.list)
routes.post('/departamentos', auth.verifyToken, departamento.save)
routes.put('/departamentos', auth.verifyToken, departamento.update)
routes.delete('/departamentos/:id', auth.verifyToken, departamento.delete)

routes.get('/centrodecustos/:id', auth.verifyToken, centroDeCusto.findById)
routes.get('/centrodecustos', auth.verifyToken, centroDeCusto.list)
routes.post('/centrodecustos', auth.verifyToken, centroDeCusto.save)
routes.put('/centrodecustos', auth.verifyToken, centroDeCusto.update)
routes.delete('/centrodecustos/:id', auth.verifyToken, centroDeCusto.delete)

routes.get('/sindicatos/:id', auth.verifyToken, sindicato.findById)
routes.get('/sindicatos', auth.verifyToken, sindicato.list)
routes.post('/sindicatos', auth.verifyToken, sindicato.save)
routes.put('/sindicatos', auth.verifyToken, sindicato.update)
routes.delete('/sindicatos/:id', auth.verifyToken, sindicato.delete)


routes.get('/colaboradores/quantidade', auth.verifyToken, colaborador.qtdColaboradores)
routes.get('/colaboradores/:id', auth.verifyToken, colaborador.findById)
routes.get('/colaboradores', auth.verifyToken, colaborador.list)
routes.post('/colaboradores', auth.verifyToken, colaborador.save)
routes.put('/colaboradores', auth.verifyToken, colaborador.update)
routes.delete('/colaboradores/:id', auth.verifyToken, colaborador.delete)

routes.get('/contadores/:id', auth.verifyToken, contador.findById)
routes.get('/contadores', auth.verifyToken, contador.list)
routes.post('/contadores', auth.verifyToken, contador.save)
routes.put('/contadores', auth.verifyToken, contador.update)
routes.delete('/contadores/:id', auth.verifyToken, contador.delete)

routes.get('/periodo-experiencias/:id', auth.verifyToken, periodoExperiencia.findById)
routes.get('/periodo-experiencias', auth.verifyToken, periodoExperiencia.list)
routes.post('/periodo-experiencias', auth.verifyToken, periodoExperiencia.save)
routes.put('/periodo-experiencias', auth.verifyToken, periodoExperiencia.update)
routes.delete('/periodo-experiencias/:id', auth.verifyToken, periodoExperiencia.delete)

routes.get('/eventos/:id', auth.verifyToken, evento.findById)
routes.get('/eventos', auth.verifyToken, evento.list)
routes.post('/eventos', auth.verifyToken, evento.save)
routes.put('/eventos', auth.verifyToken, evento.update)
routes.delete('/eventos/:id', auth.verifyToken, evento.delete)

routes.get('/lembretes/:id', auth.verifyToken, lembrete.findById)
routes.get('/lembretes', auth.verifyToken, lembrete.list)
routes.post('/lembretes', auth.verifyToken, lembrete.save)
routes.put('/lembretes', auth.verifyToken, lembrete.update)
routes.delete('/lembretes/:id', auth.verifyToken, lembrete.delete)

routes.get('/recados/:id', auth.verifyToken, recado.findById)
routes.get('/recados', auth.verifyToken, recado.list)
routes.post('/recados', auth.verifyToken, recado.save)
routes.put('/recados', auth.verifyToken, recado.update)
routes.delete('/recados/:id', auth.verifyToken, recado.delete)

routes.get('/enderecos/:id', auth.verifyToken, endereco.findById)
routes.get('/enderecos', auth.verifyToken, endereco.list)
routes.post('/enderecos', auth.verifyToken, endereco.save)
routes.put('/enderecos', auth.verifyToken, endereco.update)
routes.delete('/enderecos/:id', auth.verifyToken, endereco.delete)

routes.get('/escolaridades/:id', auth.verifyToken, escolaridade.findById)
routes.get('/escolaridades', auth.verifyToken, escolaridade.list)
routes.post('/escolaridades', auth.verifyToken, escolaridade.save)
routes.put('/escolaridades', auth.verifyToken, escolaridade.update)
routes.delete('/escolaridades/:id', auth.verifyToken, escolaridade.delete)

routes.get('/bancos/:id', auth.verifyToken, banco.findById)
routes.get('/bancos', auth.verifyToken, banco.list)
routes.post('/bancos', auth.verifyToken, banco.save)
routes.put('/bancos', auth.verifyToken, banco.update)
routes.delete('/bancos/:id', auth.verifyToken, banco.delete)

routes.get('/jornadas-trabalho/:id', auth.verifyToken, jornadaTrabalho.findById)
routes.get('/jornadas-trabalho', auth.verifyToken, jornadaTrabalho.list)
routes.post('/jornadas-trabalho', auth.verifyToken, jornadaTrabalho.save)
routes.put('/jornadas-trabalho', auth.verifyToken, jornadaTrabalho.update)
routes.delete('/jornadas-trabalho/:id', auth.verifyToken, jornadaTrabalho.delete)

routes.get('/vinculos/:id', auth.verifyToken, vinculo.findById)
routes.get('/vinculos', auth.verifyToken, vinculo.list)
routes.post('/vinculos', auth.verifyToken, vinculo.save)
routes.put('/vinculos', auth.verifyToken, vinculo.update)
routes.delete('/vinculos/:id', auth.verifyToken, vinculo.delete)

routes.get('/holerites/:id', auth.verifyToken, holerite.findById)
routes.get('/holerites', auth.verifyToken, holerite.list)
routes.post('/holerites', auth.verifyToken, holerite.save)
routes.put('/holerites', auth.verifyToken, holerite.update)
routes.delete('/holerites/:id', auth.verifyToken, holerite.delete)

routes.get('/forma-pagamentos/:id', auth.verifyToken, formaPagamento.findById)
routes.get('/forma-pagamentos', auth.verifyToken, formaPagamento.list)
routes.post('/forma-pagamentos', auth.verifyToken, formaPagamento.save)
routes.put('/forma-pagamentos', auth.verifyToken, formaPagamento.update)
routes.delete('/forma-pagamentos/:id', auth.verifyToken, formaPagamento.delete)

routes.get('/contatos/:id', auth.verifyToken, contato.findById)
routes.get('/contatos', auth.verifyToken, contato.list)
routes.post('/contatos', auth.verifyToken, contato.save)
routes.put('/contatos', auth.verifyToken, contato.update)
routes.delete('/contatos/:id', auth.verifyToken, contato.delete)
routes.get('/contatos/colaborador/:id', auth.verifyToken, contato.listByColaborador)

routes.get('/copia-documentos/:id', auth.verifyToken, copiaDocumento.findById)
routes.get('/copia-documentos', auth.verifyToken, copiaDocumento.list)
routes.post('/copia-documentos', auth.verifyToken, copiaDocumento.save)
routes.put('/copia-documentos', auth.verifyToken, copiaDocumento.update)
routes.delete('/copia-documentos/:id', auth.verifyToken, copiaDocumento.delete)

routes.get('/checklists/:id', auth.verifyToken, checklist.findById)
routes.get('/checklists', auth.verifyToken, checklist.list)
routes.post('/checklists', auth.verifyToken, checklist.save)
routes.put('/checklists', auth.verifyToken, checklist.update)
routes.delete('/checklists/:id', auth.verifyToken, checklist.delete)
routes.get('/checklists/colaborador/:id', auth.verifyToken, checklist.listByColaborador)


routes.get('/dependentes/:id', auth.verifyToken, dependente.findById)
routes.get('/dependentes', auth.verifyToken, dependente.list)
routes.post('/dependentes', auth.verifyToken, dependente.save)
routes.put('/dependentes', auth.verifyToken, dependente.update)
routes.delete('/dependentes/:id', auth.verifyToken, dependente.delete)
routes.get('/dependentes/colaborador/:id', auth.verifyToken, dependente.listByColaborador)

routes.get('/beneficios/:id', auth.verifyToken, beneficio.findById)
routes.get('/beneficios', auth.verifyToken, beneficio.list)
routes.post('/beneficios', auth.verifyToken, beneficio.save)
routes.put('/beneficios', auth.verifyToken, beneficio.update)
routes.delete('/beneficios/:id', auth.verifyToken, beneficio.delete)

routes.get('/configuracaos/:id', auth.verifyToken, configuracao.findById)
routes.get('/configuracaos', auth.verifyToken, configuracao.list)
routes.post('/configuracaos', auth.verifyToken, configuracao.save)
routes.put('/configuracaos', auth.verifyToken, configuracao.update)
routes.delete('/configuracaos/:id', auth.verifyToken, configuracao.delete)

routes.get('/feriados/restaure', auth.verifyToken, feriado.delete)
routes.get('/feriados/:id', auth.verifyToken, feriado.findById)
routes.get('/feriados', auth.verifyToken, feriado.list)
routes.post('/feriados', auth.verifyToken, feriado.save)
routes.put('/feriados', auth.verifyToken, feriado.update)
routes.delete('/feriados/:id', auth.verifyToken, feriado.delete)

routes.get('/fechamento-folhas/:id', auth.verifyToken, fechamentoFolha.findById)
routes.get('/fechamento-folhas', auth.verifyToken, fechamentoFolha.list)
routes.post('/fechamento-folhas', auth.verifyToken, fechamentoFolha.save)
routes.put('/fechamento-folhas', auth.verifyToken, fechamentoFolha.update)
routes.delete('/fechamento-folhas/:id', auth.verifyToken, fechamentoFolha.delete)

routes.get('/empresas/restaure', auth.verifyToken, empresa.delete)
routes.get('/empresas/:id', auth.verifyToken, empresa.findById)
routes.get('/empresas', auth.verifyToken, empresa.list)
routes.post('/empresas', auth.verifyToken, empresa.save)
routes.put('/empresas', auth.verifyToken, empresa.update)
routes.delete('/empresas/:id', auth.verifyToken, empresa.delete)

routes.get('/cobrancas/restaure', auth.verifyToken, cobranca.delete)
routes.get('/cobrancas/:id', auth.verifyToken, cobranca.findById)
routes.get('/cobrancas', auth.verifyToken, cobranca.list)
routes.post('/cobrancas', auth.verifyToken, cobranca.save)
routes.put('/cobrancas', auth.verifyToken, cobranca.update)
routes.delete('/cobrancas/:id', auth.verifyToken, cobranca.delete)

routes.get('/companhias/:id', auth.verifyToken, companhia.findById)
routes.get('/companhias', auth.verifyToken, companhia.list)
routes.post('/companhias', companhia.save)
routes.put('/companhias', auth.verifyToken, companhia.update)
routes.delete('/companhias/:id', auth.verifyToken, companhia.delete)

routes.get('/usuarios/logged', auth.verifyToken, usuario.userLogged)
routes.put('/usuarios/update-password', auth.verifyToken, usuario.updatePassword)
routes.get('/usuarios/:id', auth.verifyToken, usuario.findById)
routes.get('/usuarios', auth.verifyToken, usuario.list)
routes.post('/usuarios', usuario.save)
routes.put('/usuarios', auth.verifyToken, usuario.update)
routes.delete('/usuarios/:id', auth.verifyToken, usuario.delete)

routes.post('/login', auth.login)

module.exports = routes
