const routes = require('express').Router()

const cargo = require('./cargo')
const centroDeCusto = require('./centroDeCusto')
const contador = require('./contador')
const departamento = require('./departamento')
const sindicato = require('./sindicato')
const colaborador  = require('./colaborador')
const periodoExperiencia  = require('./periodoExperiencia')
const evento  = require('./evento')
const lembrete  = require('./lembrete')
const recado  = require('./recado')
const endereco  = require('./endereco')

routes.get('/cargos/:id', cargo.findById)
routes.get('/cargos', cargo.list)
routes.post('/cargos', cargo.save)
routes.put('/cargos', cargo.update)
routes.delete('/cargos/:id', cargo.delete)

routes.get('/departamentos/:id', departamento.findById)
routes.get('/departamentos', departamento.list)
routes.post('/departamentos', departamento.save)
routes.put('/departamentos', departamento.update)
routes.delete('/departamentos/:id', departamento.delete)

routes.get('/centrodecustos/:id', centroDeCusto.findById)
routes.get('/centrodecustos', centroDeCusto.list)
routes.post('/centrodecustos', centroDeCusto.save)
routes.put('/centrodecustos', centroDeCusto.update)
routes.delete('/centrodecustos/:id', centroDeCusto.delete)

routes.get('/sindicatos/:id', sindicato.findById)
routes.get('/sindicatos', sindicato.list)
routes.post('/sindicatos', sindicato.save)
routes.put('/sindicatos', sindicato.update)
routes.delete('/sindicatos/:id', sindicato.delete)

routes.get('/colaboradores/:id', colaborador.findById)
routes.get('/colaboradores', colaborador.list)
routes.post('/colaboradores', colaborador.save)
routes.put('/colaboradores', colaborador.update)
routes.delete('/colaboradores/:id', colaborador.delete)

routes.get('/contadores/:id',contador.findById)
routes.get('/contadores',contador.list)
routes.post('/contadores',contador.save)
routes.put('/contadores',contador.update)
routes.delete('/contadores/:id',contador.delete)

routes.get('/periodo-experiencias/:id',periodoExperiencia.findById)
routes.get('/periodo-experiencias',periodoExperiencia.list)
routes.post('/periodo-experiencias',periodoExperiencia.save)
routes.put('/periodo-experiencias',periodoExperiencia.update)
routes.delete('/periodo-experiencias/:id',periodoExperiencia.delete)

routes.get('/eventos/:id',evento.findById)
routes.get('/eventos',evento.list)
routes.post('/eventos',evento.save)
routes.put('/eventos',evento.update)
routes.delete('/eventos/:id',evento.delete)

routes.get('/lembretes/:id',lembrete.findById)
routes.get('/lembretes',lembrete.list)
routes.post('/lembretes',lembrete.save)
routes.put('/lembretes',lembrete.update)
routes.delete('/lembretes/:id',lembrete.delete)

routes.get('/recados/:id',recado.findById)
routes.get('/recados',recado.list)
routes.post('/recados',recado.save)
routes.put('/recados',recado.update)
routes.delete('/recados/:id',recado.delete)

routes.get('/enderecos/:id',endereco.findById)
routes.get('/enderecos',endereco.list)
routes.post('/enderecos',endereco.save)
routes.put('/enderecos',endereco.update)
routes.delete('/enderecos/:id',endereco.delete)

module.exports = routes
